### ISSUE TITLE
Add shortcut feature

### ISSUE THREAD

**Issue by me7tarfeek** [duzhaokun123/YAMF#11]
### Description

Need the ability to run application shortcut from Tasker for example to start any app in Freeform using YAFM

**Comment by duzhaokun123** [comment]
boardcast
- `io.github.duzhaokun123.yamf.action.CURRENT_TO_WINDOW`
- `io.github.duzhaokun123.yamf.action.OPEN_APP_LIST`

**Comment by duzhaokun123** [comment]
and `io.github.duzhaokun123.yamf.action.OPEN_APP`

see https://github.com/duzhaokun123/YAMF/blob/9838dc93985aba8610c598140a33a8c02d023a1e/app/src/main/java/io/github/duzhaokun123/yamf/xposed/services/YAMFManager.kt#L209-L215

i'm not sure if it work when call from command line

**Comment by me7tarfeek** [comment]
Thanks a lot… the first two broadcast is good enough.. 
I launch any app I want, then run the command: 
am broadcast -a io.github.duzhaokun123.yamf.action.CURRENT_TO_WINDOW

And it opens in freeform… 👍

Great work… thanks

**Comment by me7tarfeek** [comment]
Thanks a lot
