### ISSUE TITLE
[bug]启用对 Lawnchair 桌面的 hook 会导致系统重启

### ISSUE THREAD

**Issue by 4455bk** [duzhaokun123/YAMF#13]
### 复现步骤

LSPosed 作用域勾选 Lawnchair 14 Dev (#442)

### 预期行为

可在最近任务界面和桌面 shortcut 启动小窗，以前是可以的，今天更新系统后就不行了

### 实际行为

系统重启

### Xposed 框架

LSPosed 1.9.2 (7058)

### Android 版本

crDroid Android 14

### YAMF 版本

0.7-git.9838dc9

### 版本要求

- [x] 我正在使用最新 ci 的 dubug 的 YAMF

### 日志

[LSPosed_2024-02-02T17_59_12.339165.zip](https://github.com/duzhaokun123/YAMF/files/14138438/LSPosed_2024-02-02T17_59_12.339165.zip)

**Comment by 4455bk** [comment]
日志里面看到 system restart 了

**Comment by duzhaokun123** [comment]
```
[ 2024-02-02T17:57:50.678     1000:  1806:  1806 I/LSPosed-Bridge  ] [YAMFManager] YAMF service initialized
[ 2024-02-02T17:57:50.728     1000:  1806:  1806 I/LSPosed-Bridge  ] [E/EZXHelper] : java.lang.NullPointerException: Parameter specified as non-null is null: method io.github.duzhaokun123.yamf.xposed.services.YAMFManager.setConfig, parameter <set-?>
	at io.github.duzhaokun123.yamf.xposed.services.YAMFManager.setConfig(Unknown Source:2)
	at io.github.duzhaokun123.yamf.xposed.services.YAMFManager.systemReady(Unknown Source:130)
```
也就是
https://github.com/duzhaokun123/YAMF/blob/9838dc93985aba8610c598140a33a8c02d023a1e/app/src/main/java/io/github/duzhaokun123/yamf/xposed/services/YAMFManager.kt#L95-L97
`gson.fromJson(configFile.readText(), Config::class.java)`返回了`null`
🤔

**Comment by duzhaokun123** [comment]
```java
  /**
   * @return an object of type T from the string. Returns {@code null} if {@code json} is {@code null}
   * or if {@code json} is empty.
   ...
  */
  public <T> T fromJson(String json, Class<T> classOfT) throws JsonSyntaxException {
    T object = fromJson(json, TypeToken.get(classOfT));
    return Primitives.wrap(classOfT).cast(object);
  }
```
也就是说`/data/system/yamf.json`是空的json
也许删掉就好了 但为什么会变成空的

**Comment by duzhaokun123** [comment]
fix https://github.com/duzhaokun123/YAMF/commit/1775e5bf4b3f2d6a925d9a5d7426afd525127487

**Comment by 4455bk** [comment]
> fix [1775e5b](https://github.com/duzhaokun123/YAMF/commit/1775e5bf4b3f2d6a925d9a5d7426afd525127487)

好好好
