### ISSUE TITLE
通过命令/xposededge打开“打开应用列表”和"开窗"“进窗”功能

### ISSUE THREAD

**Issue by yutouyes** [duzhaokun123/YAMF#4]
作者你好，yamf很好用，非常感谢，但“打开应用列表”功能目前我只知道长按x和在app中打开，"开窗"“进窗”功能可以在app和磁贴中打开，都不是很方便，现在想通过执行命令或者xposed edge的手势功能直接呼出“打开应用列表”和"开窗"功能，请问应该怎么做？
搜索不到对应的活动，所以创建快捷方式的办法没有作用

**Comment by duzhaokun123** [comment]
已实现 https://github.com/duzhaokun123/YAMF/commit/4c9e16f31207f9c8dab19f6eba57751b5812e12c

**Comment by yutouyes** [comment]
> 已实现 [4c9e16f](https://github.com/duzhaokun123/YAMF/commit/4c9e16f31207f9c8dab19f6eba57751b5812e12c)
![Screenshot_2023-05-04-22-37-39-42_a5c17d2e2fb3cc7](https://user-images.githubusercontent.com/17039457/236241171-f15d2991-eaae-4d35-afa5-97fa29c56c52.jpg)
![Screenshot_2023-05-04-22-38-03-95_9458954033fdd07](https://user-images.githubusercontent.com/17039457/236241300-fdec66e7-f11a-44bb-835b-957c196e7f2c.jpg)
尝试在终端中广播，没有执行对应功能，xposed edge中也是相同情况。设备是安卓12的realme x50pro，系统是coloros12换皮

**Comment by yutouyes** [comment]
> Reference

是在[这里](https://github.com/Xposed-Modules-Repo/io.github.duzhaokun123.yamf/releases)下载吗，还是4天前的版本

**Comment by yutouyes** [comment]
> 更新到 [4c9e16f](https://github.com/duzhaokun123/YAMF/commit/4c9e16f31207f9c8dab19f6eba57751b5812e12c) 了吗

是在[这里](https://github.com/Xposed-Modules-Repo/io.github.duzhaokun123.yamf/releases)下载吗，还是4天前的版本

**Comment by duzhaokun123** [comment]
https://github.com/duzhaokun123/YAMF/actions?query=branch%3Amain

**Comment by yutouyes** [comment]
> 4c9e16f

ok，确认可用
