### ISSUE TITLE
[Feature Request] Lawnchair support

### ISSUE THREAD

**Issue by gaussandhisgun** [duzhaokun123/YAMF#9]
### Description

As of now, YAMF's xposed hooks dont work on [Lawnchair](https://github.com/LawnchairLauncher/lawnchair) 14-dev. It would be cool if they did.

### Describe the solution you'd like

You know, just like in Pixel Launcher?

### Describe alternatives you've considered

Whatever Pixel Launcher builds are available for my device, usually either dont work or look bad. Lawnchair is trying to get a single launcher to work on any Quickswitch-compatible device from Android 10 to Android 14. This is what 14-dev is all about. And so far, YAMF does not work with it.

**Comment by duzhaokun123** [comment]
it's a bug that launcher hook broken after target api 34 as registerReceiver miss RECEIVER_EXPORTED flag

**Comment by gaussandhisgun** [comment]
oh, so it should be a one line fix, *right*?

**Comment by duzhaokun123** [comment]
fixed https://github.com/duzhaokun123/YAMF/commit/5ac764d2596d5d95657c4d670369d20ca5d18d37
